// Rules for the rest of the card pool (everything outside the top meta cards
// in abilities.js). Same hooks as abilities.js, plus:
//   allyPlayed(g, c, played)     after you play a card anywhere
//   anyPlayedHere(g, c, played)  after ANY card is played at this card's location
//   cardMovedHere(g, c, moved)   when a card moves to this card's location
//   allyDestroyed(g, c, dead)    when another of your cards is destroyed
// and g.laneBonus(lane, side, n) for Power added to a whole side of a location.

const other = (s) => (s === 'me' ? 'opp' : 'me');
const mine = (g, c) => g.at(c.lane, c.side).filter((x) => x !== c);
const enemy = (g, c) => g.at(c.lane, other(c.side));
const allies = (g, c) => g.active().filter((x) => x.side === c.side && x !== c);
const foes = (g, c) => g.active().filter((x) => x.side !== c.side);
const byPower = (g) => (a, b) => g.power(b) - g.power(a);
const lowest = (g, list) => list.slice().sort((a, b) => g.power(a) - g.power(b))[0];
const cost = (g, x) => g.info(x).cost;
const text = (g, x) => g.info(x).ability || '';
const pend = (g, c, label, fn) => g.pending.push({ side: c.side, src: c.uid, label, fn });
const freeLane = (g, side, not) => [0, 1, 2].filter((l) => l !== not && !g.full(l, side)).sort((a, b) => g.at(a, side).length - g.at(b, side).length)[0];
const winning = (g, c) => { g.computeLive(); return g.sideTotal(c.lane, c.side) > g.sideTotal(c.lane, other(c.side)); };

const M = (note, hooks) => ({ kind: 'modelled', note, ...hooks });
const A = (note, hooks) => ({ kind: 'approx', note, ...hooks });
const N = (note) => ({ kind: 'none', note });

// Hand, deck, draw, cost and energy effects: real, but they don't change the
// board directly (the win chance uses your marked hand and energy instead).
const HAND = 'Changes cards in hand.';
const DECK = 'Changes cards in a deck.';
const DRAW = 'Draws or adds cards to hand.';
const COST = 'Changes costs.';
const ENERGY = 'Changes energy.';
const DISCARD = 'Discards from hand.';
const PLAYRULE = 'Only limits where it can be played.';

export const MORE_ABILITIES = {
  // ---- On Reveal: Power for itself --------------------------------------
  Medusa: M('+3 at the middle location.', { reveal: (g, c) => { if (c.lane === 1) g.buff(c, 3); } }),
  Wolfsbane: M('+2 for each of your other cards here.', { reveal: (g, c) => g.buff(c, 2 * mine(g, c).length) }),
  HitMonkey: M('+2 for each other card you played this turn.', { reveal: (g, c) => g.buff(c, 2 * g.playedThisTurn(c.side).filter((x) => x !== c).length) }),
  Groot: M('+4 if the opponent played a card here this turn.', { reveal: (g, c) => { if (g.oppPlayedHere(c)) g.buff(c, 4); } }),
  Gamora: M('+4 if the opponent played a card here this turn.', { reveal: (g, c) => { if (g.oppPlayedHere(c)) g.buff(c, 4); } }),
  Drax: M('+4 if the opponent played a card here this turn.', { reveal: (g, c) => { if (g.oppPlayedHere(c)) g.buff(c, 4); } }),
  Starlord: M('+4 if the opponent played a card here this turn.', { reveal: (g, c) => { if (g.oppPlayedHere(c)) g.buff(c, 4); } }),
  RocketRaccoon: M('+4 if the opponent played a card here this turn.', { reveal: (g, c) => { if (g.oppPlayedHere(c)) g.buff(c, 4); } }),
  DraxGuardiansOfTheGalaxy: M('Doubles if the opponent played a card here this turn.', { reveal: (g, c) => { if (g.oppPlayedHere(c)) g.buff(c, g.power(c)); } }),
  RedHulkFracturedFrontier: A('−1 for each enemy card here (Quickdraw not tracked).', { reveal: (g, c) => g.buff(c, -enemy(g, c).length) }),
  Taskmaster: M('Copies the Power of the last card you played.', { reveal: (g, c) => { const t = g.lastPlayed[c.side]; if (t && t !== c) g.setPower(c, g.power(t)); } }),
  TaskmasterThunderbolts: A('Gains the Power of your strongest other card.', { reveal: (g, c) => { const t = allies(g, c).sort(byPower(g))[0]; if (t) g.buff(c, g.power(t)); } }),
  Sage: M('+2 for each different Power among other cards here.', { reveal: (g, c) => g.buff(c, 2 * new Set(g.at(c.lane).filter((x) => x !== c).map((x) => g.power(x))).size) }),
  Laufey: M('Steals 1 Power from each other card here.', { reveal: (g, c) => g.at(c.lane).filter((x) => x !== c).forEach((x) => { g.buff(x, -1); g.buff(c, 1); }) }),
  Gilgamesh: M('+1 for each of your other cards with increased Power.', { reveal: (g, c) => g.buff(c, allies(g, c).filter((x) => g.power(x) > g.info(x).power).length) }),
  Ares: A('+6 if the top of your deck beats theirs (assumed half the time).', { reveal: (g, c) => g.buff(c, 3) }),
  Blob: A('Merges deck cards until it gains 13+ (counted as 14).', { reveal: (g, c) => g.buff(c, 14) }),
  Random: A('Becomes the Power of a random deck card (counted as an average card).', { reveal: (g, c) => g.setPower(c, Math.round(g.avgPower(3))) }),
  Kraglin: A('+4 or +2 energy next turn (counted as +2).', { reveal: (g, c) => g.buff(c, 2) }),
  RedWolfFracturedFrontier: A('+1 for each card in hand (counted as 3).', { reveal: (g, c) => g.buff(c, 3) }),
  GhostTheFirstRider: A('Loses a discarded card’s Power (counted as −3).', { reveal: (g, c) => g.buff(c, -3) }),
  FinFangFoom: A('Gains the Power of the strongest enemy card here.', { reveal: (g, c) => { const t = enemy(g, c).sort(byPower(g))[0]; if (t) g.buff(c, g.power(t)); } }),
  HulkAvengers: A('+2 for each of your other cards here (Avengers not tracked).', { reveal: (g, c) => g.buff(c, 2 * mine(g, c).length) }),

  // ---- On Reveal: Power for others ----------------------------------------
  WhiteTiger: M('Adds a 10-Power Tiger to another location.', { reveal: (g, c) => { const l = freeLane(g, c.side, c.lane); if (l != null) g.spawn(c.side, 'TigerSpirit', l, 10, c.uid); } }),
  Spectrum: M('Your Ongoing cards get +2.', { reveal: (g, c) => allies(g, c).filter((x) => /Ongoing/.test(text(g, x))).forEach((x) => g.buff(x, 2)) }),
  Namora: M('+5 to each of your cards alone at another location.', { reveal: (g, c) => [0, 1, 2].filter((l) => l !== c.lane).forEach((l) => { const here = g.at(l, c.side); if (here.length === 1) g.buff(here[0], 5); }) }),
  Aurora: A('+2 to one of your other cards at each location.', { reveal: (g, c) => [0, 1, 2].forEach((l) => { const t = g.at(l, c.side).filter((x) => x !== c && /On Reveal|Ongoing|Activate|End of Turn/.test(text(g, x))).sort(byPower(g))[0]; if (t) g.buff(t, 2); }) }),
  Starhawk: M('+1 to your cards at the left (odd turn) or right (even turn) location.', { reveal: (g, c) => { const l = g.turn % 2 ? 0 : 2; g.at(l, c.side).forEach((x) => g.buff(x, 1)); } }),
  ShouLao: A('Gives your last card +2 per turn you played 2+ cards (not tracked).', {}),
  Triton: A('+3 to the last card each player played last turn.', { reveal: (g, c) => ['me', 'opp'].forEach((s) => { const t = g.board.filter((x) => x.side === s && !x.gone && x.lane != null && x.turn === g.turn - 1).pop(); if (t) g.buff(t, 3); }) }),
  SpiderSense: M('Your cards here get +3.', { reveal: (g, c) => mine(g, c).forEach((x) => g.buff(x, 3)) }),
  Valkyrie: M('Sets ALL cards here to 3 Power.', { reveal: (g, c) => g.at(c.lane).forEach((x) => g.setPower(x, 3)) }),
  Kahhori: A('Each card in hand gives one of your cards +1 (counted as 3).', { reveal: (g, c) => { const t = allies(g, c).sort(byPower(g)); for (let i = 0; i < 3 && t.length; i++) g.buff(t[i % t.length], 1); } }),
  MrSinister: M('Adds a Sinister Clone here with the same Power.', { reveal: (g, c) => g.spawn(c.side, 'SinisterClone', c.lane, g.power(c), c.uid) }),
  Ultron: M('Adds 2-Power Drones to each other location.', { reveal: (g, c) => [0, 1, 2].filter((l) => l !== c.lane).forEach((l) => { while (!g.full(l, c.side) && g.spawn(c.side, 'Drone', l, 2, c.uid)); }) }),
  Debrii: M('Adds a Rock to each other location (both sides).', { reveal: (g, c) => [0, 1, 2].filter((l) => l !== c.lane).forEach((l) => { g.spawn('me', 'Rock', l, 0, c.uid); g.spawn('opp', 'Rock', l, 0, c.uid); }) }),
  Rhino: M('Adds a Rock on your side here.', { reveal: (g, c) => g.spawn(c.side, 'Rock', c.lane, 0, c.uid) }),
  LinLie: A('Adds the Sword of Fu Xi to another location.', { reveal: (g, c) => { const l = freeLane(g, c.side, c.lane); if (l != null) g.spawn(c.side, 'SwordOfFuXi', l, null, c.uid); } }),
  Sentry: M('Adds a −9 Void to the right location.', { reveal: (g, c) => { if (c.lane < 2) g.spawn(c.side, 'TheVoid', 2, -9, c.uid); } }),
  SentryThunderbolts: A('Adds a −9 Void to another location.', { reveal: (g, c) => { const l = freeLane(g, c.side, c.lane); if (l != null) g.spawn(c.side, 'TheVoid', l, -9, c.uid); } }),
  Shanna: A('Adds a random 1-Cost card to each location (about 2 Power each).', { reveal: (g, c) => [0, 1, 2].forEach((l) => g.spawn(c.side, 'Squirrel', l, 2, c.uid)) }),
  WhiteWidow: M('Adds Widow’s Kiss to the enemy side here.', { reveal: (g, c) => g.spawn(other(c.side), 'WidowsKiss', c.lane, null, c.uid) }),
  Mysterio: A('Adds an Illusion to another location.', { reveal: (g, c) => { const l = freeLane(g, c.side, c.lane); if (l != null) g.spawn(c.side, 'MysterioIllusion', l, null, c.uid); } }),
  Malekith: A('Adds a hidden 3-Cost card from your deck here (about 4 Power).', { reveal: (g, c) => g.spawn(c.side, 'Squirrel', c.lane, Math.round(g.avgPower(3)), c.uid) }),
  JubileeXMen: A('Adds the top deck card here (log it with "+ Add card").', {}),
  DragonLord: A('Puts a card from hand here (log it with "+ Add card").', {}),
  BaronZemo: A('Recruits a cheap enemy deck card here (log it with "+ Add card").', {}),
  Yellowjacket: M('Your other cards here get −1.', { reveal: (g, c) => mine(g, c).forEach((x) => g.buff(x, -1)) }),

  // ---- On Reveal: against the enemy -------------------------------------
  LadyBullseye: A('−2 to an enemy card (repeats per unspent energy; counted once).', { reveal: (g, c) => { const t = foes(g, c).sort(byPower(g))[0]; if (t) g.buff(t, -2); } }),
  SpiderWoman: M('All enemy cards here get −1.', { reveal: (g, c) => enemy(g, c).forEach((x) => g.buff(x, -1)) }),
  Elektra: M('Destroys an enemy 1-Cost card here.', { reveal: (g, c) => { const t = enemy(g, c).filter((x) => cost(g, x) === 1).sort(byPower(g))[0]; if (t) g.destroy(t); } }),
  LadyDeathstrike: M('Destroys each card here with 3 or less Power.', { reveal: (g, c) => g.at(c.lane).filter((x) => x !== c && g.power(x) <= 3).forEach((x) => g.destroy(x)) }),
  LadyDeathstrikeBrotherhoodOfMutants: A('Destroys a weaker enemy card here.', { reveal: (g, c) => { const t = enemy(g, c).filter((x) => g.power(x) < g.power(c)).sort(byPower(g))[0]; if (t) g.destroy(t); } }),
  GamoraGuardiansOfTheGalaxy: M('Destroys their cheapest card here if they played here this turn.', { reveal: (g, c) => { if (!g.oppPlayedHere(c)) return; const t = enemy(g, c).sort((a, b) => cost(g, a) - cost(g, b))[0]; if (t) g.destroy(t); } }),
  Cannonball: A('Moves the strongest enemy card here away.', { reveal: (g, c) => { const t = enemy(g, c).sort(byPower(g))[0]; if (t && !g.move(t, freeLane(g, t.side, c.lane))) g.destroy(t); } }),
  Aero: M('Pulls the last card the opponent played here.', { reveal: (g, c) => { const t = g.lastPlayed[other(c.side)]; if (t) g.move(t, c.lane); } }),
  Stegron: M('Moves an enemy card here one location right.', { reveal: (g, c) => { const t = enemy(g, c).sort(byPower(g))[0]; if (t && c.lane < 2) g.move(t, c.lane + 1); } }),
  Viper: M('Your weakest other card here switches sides.', { reveal: (g, c) => { const t = lowest(g, mine(g, c)); if (t && !g.full(c.lane, other(c.side))) t.side = other(t.side); } }),
  Hobgoblin: M('Switches to the enemy side.', { reveal: (g, c) => { if (!g.full(c.lane, other(c.side))) c.side = other(c.side); } }),
  GreenGoblin: M('Switches to the enemy side.', { reveal: (g, c) => { if (!g.full(c.lane, other(c.side))) c.side = other(c.side); } }),
  Annihilus: M('Your negative-Power cards switch sides.', { reveal: (g, c) => allies(g, c).filter((x) => g.power(x) < 0).forEach((x) => { if (!g.full(x.lane, other(x.side))) x.side = other(x.side); else g.destroy(x); }) }),
  CosmicGhostRider: A('Removes text from front-row enemy cards here.', { reveal: (g, c) => enemy(g, c).slice(0, 2).forEach((x) => { x.silenced = true; }) }),
  Alioth: A('Removes text from enemy cards here.', { reveal: (g, c) => enemy(g, c).filter((x) => x.turn === g.turn).forEach((x) => { x.silenced = true; }) }),
  DeafeningChord: M('Removes the text of a 3-Cost or lower enemy card here.', { reveal: (g, c) => { const t = enemy(g, c).find((x) => cost(g, x) <= 3); if (t) t.silenced = true; } }),
  Ghost: M('Removes End of Turn abilities here.', { reveal: (g, c) => g.at(c.lane).forEach((x) => { if (x !== c && /End of Turn/.test(text(g, x))) x.silenced = true; }) }),
  TheInversion: M('Inverts the Power of the lowest card(s) here.', { reveal: (g, c) => { const here = g.at(c.lane).filter((x) => x !== c); const lo = Math.min(...here.map((x) => g.power(x))); here.filter((x) => g.power(x) === lo).forEach((x) => g.setPower(x, -g.power(x))); } }),
  Leader: M('Copies the strongest enemy card played this turn to your side.', { reveal: (g, c) => { const t = g.playedThisTurn(other(c.side)).filter((x) => !x.gone && x.lane != null).sort(byPower(g))[0]; if (t) { const k = g.spawn(c.side, t.id, c.lane, g.power(t), c.uid); if (k) k.created = true; } } }),
  MagnetoBrotherhoodOfMutants: A('Moves an enemy 3 and 4-Cost card away, stealing 1 each.', { reveal: (g, c) => [3, 4].forEach((k) => { const t = enemy(g, c).find((x) => cost(g, x) === k); if (t) { g.buff(t, -1); g.buff(c, 1); g.move(t, freeLane(g, t.side, c.lane)); } }) }),
  DoctorOctopus: A('Pulls their weakest hand card to their side here (about 3 Power).', { reveal: (g, c) => g.spawn(other(c.side), 'Squirrel', c.lane, 3, c.uid) }),
  SpiderMan: A('Moves to another location and pulls an enemy card with it.', { reveal: (g, c) => { const t = enemy(g, c).sort(byPower(g))[0]; const from = c.lane; const l = freeLane(g, c.side, from); if (l != null && g.move(c, l, 'self') && t) g.move(t, l); } }),

  // ---- On Reveal: destroy, move, merge your own ----------------------------
  Destroyer: M('Destroys your cards at the other locations.', { reveal: (g, c) => allies(g, c).filter((x) => x.lane !== c.lane).forEach((x) => g.destroy(x)) }),
  Tombstone: M('Destroys your weakest card at each other location.', { reveal: (g, c) => [0, 1, 2].filter((l) => l !== c.lane).forEach((l) => { const t = lowest(g, g.at(l, c.side)); if (t) g.destroy(t); }) }),
  Misery: M('Repeats your other On Reveals here, then destroys them.', { reveal: (g, c) => mine(g, c).forEach((x) => { g.runReveal(x); g.destroy(x); }) }),
  FriendlyNeighborhoodCarnage: M('Moves your other cards here right, +2 each.', { reveal: (g, c) => mine(g, c).forEach((x) => { if (c.lane < 2 && g.move(x, c.lane + 1)) g.buff(c, 2); }) }),
  Toad: M('The last card you played moves here.', { reveal: (g, c) => { const t = g.lastPlayed[c.side]; if (t && t !== c) g.move(t, c.lane); } }),
  GhostSpiderWebSlingers: M('The last card you played moves here.', { reveal: (g, c) => { const t = g.lastPlayed[c.side]; if (t && t !== c) g.move(t, c.lane); } }),
  ManSpider: M('Merges your last card into this, doubled.', { reveal: (g, c) => { const t = g.lastPlayed[c.side]; if (t && t !== c && !t.gone) { g.buff(c, 2 * g.power(t)); t.gone = 'merged'; } } }),
  ThePhoenixForce: A('Revives your strongest destroyed card and merges into it.', { reveal: (g, c) => { const t = g.board.filter((x) => x.gone === 'destroyed' && x.side === c.side).sort(byPower(g))[0]; if (t) { const k = g.copy(t, c.lane); if (k) g.buff(k, g.power(c)); c.gone = 'merged'; } } }),
  Firelord: A('Revives one of your destroyed 3-Costs here.', { reveal: (g, c) => { const t = g.board.filter((x) => x.gone === 'destroyed' && x.side === c.side && cost(g, x) === 3).sort(byPower(g))[0]; if (t) g.copy(t, c.lane); } }),
  Elixir: A('Revives a card destroyed last turn here.', { reveal: (g, c) => { const t = g.board.filter((x) => x.gone === 'destroyed' && x.side === c.side).pop(); if (t) g.copy(t, c.lane); } }),
  DeathFracturedFrontier: A('Resurrects all your destroyed cards.', { reveal: (g, c) => g.board.filter((x) => x.gone === 'destroyed' && x.side === c.side).forEach((x) => { const l = freeLane(g, c.side); if (l != null) g.copy(x, l); }) }),
  Beast: M('Returns your other cards here to hand.', { reveal: (g, c) => mine(g, c).forEach((x) => { x.gone = 'hand'; }) }),
  Toxin: M('Returns your other cards here to hand, +2 each.', { reveal: (g, c) => mine(g, c).forEach((x) => { x.gone = 'hand'; g.buff(c, 2); }) }),
  Falcon: M('Returns your 1-Costs to hand.', { reveal: (g, c) => allies(g, c).filter((x) => cost(g, x) === 1).forEach((x) => { x.gone = 'hand'; }) }),
  DoctorStrangeAvengers: A('Moves one of your On Reveal cards here and repeats it.', { reveal: (g, c) => { const t = allies(g, c).filter((x) => x.lane !== c.lane && g.abilityOf(x)?.reveal).sort(byPower(g))[0]; if (t && g.move(t, c.lane)) g.runReveal(t); } }),
  Chameleon: A('Copies the On Reveal of another card here you played this turn.', { reveal: (g, c) => { const t = mine(g, c).find((x) => x.turn === g.turn && g.abilityOf(x)?.reveal); if (t) g.runReveal(t, g.abilityOf(t), c); } }),
  Morph: A('Becomes a copy of a card in the opponent’s hand (set its ability on the board).', {}),

  // ---- Ongoing ------------------------------------------------------------
  CaptainAmerica: M('Your other Ongoing cards here have +2.', { ongoing: (g, c, add) => mine(g, c).filter((x) => /Ongoing/.test(text(g, x))).forEach((x) => add(x, 2)) }),
  CaptainAmericaAvengers: A('Your other cards here have +2 (Avengers not tracked).', { ongoing: (g, c, add) => mine(g, c).forEach((x) => add(x, 2)) }),
  Patriot: M('Your cards with no abilities have +2.', { ongoing: (g, c, add) => allies(g, c).filter((x) => !g.info(x).special).forEach((x) => add(x, 2)) }),
  VictoriaHand: A('Your cards created in hand have +2.', { ongoing: (g, c, add) => allies(g, c).filter((x) => x.created).forEach((x) => add(x, 2)) }),
  Lizard: M('−4 if the opponent has 4 cards here.', { ongoing: (g, c, add) => { if (enemy(g, c).length >= 4) add(c, -4); } }),
  Starbrand: M('The opponent has +3 at each other location.', { ongoing: (g, c) => [0, 1, 2].filter((l) => l !== c.lane).forEach((l) => g.laneBonus(l, other(c.side), 3)) }),
  MrFantastic: M('Adjacent locations have +3 (for you).', { ongoing: (g, c) => [c.lane - 1, c.lane + 1].forEach((l) => g.laneBonus(l, c.side, 3)) }),
  Klaw: M('The location to the right has +6 (for you).', { ongoing: (g, c) => g.laneBonus(c.lane + 1, c.side, 6) }),
  OmegaRed: M('If winning here, +3 at other locations.', { ongoing: (g, c) => { const mineP = g.at(c.lane, c.side).reduce((s, x) => s + g.power(x), 0); const theirs = g.at(c.lane, other(c.side)).reduce((s, x) => s + g.power(x), 0); if (mineP > theirs) [0, 1, 2].filter((l) => l !== c.lane).forEach((l) => g.laneBonus(l, c.side, 3)); } }),
  MsMarvel: A('+6 at adjacent locations with 2+ of your cards and no repeated costs.', { ongoing: (g, c) => [c.lane - 1, c.lane + 1].filter((l) => l >= 0 && l <= 2).forEach((l) => { const h = g.at(l, c.side); const costs = h.map((x) => cost(g, x)); if (h.length >= 2 && new Set(costs).size === costs.length) g.laneBonus(l, c.side, 6); }) }),
  CaptainCarter: A('Adds its Power to your back-row cards here.', { ongoing: (g, c, add) => mine(g, c).slice(2).forEach((x) => add(x, g.power(c))) }),
  HydraStomper: A('+1 per move of your cards this game.', { ongoing: (g, c, add) => add(c, g.board.filter((x) => x.side === c.side).reduce((s, x) => s + (x.moves || 0), 0)) }),
  Goliath: M('+1 for each of your other Ongoing cards in play.', { ongoing: (g, c, add) => add(c, allies(g, c).filter((x) => /Ongoing/.test(text(g, x))).length) }),
  Punisher: M('+1 for each enemy card here.', { ongoing: (g, c, add) => add(c, enemy(g, c).length) }),
  Namor: M('+5 if it’s your only card here.', { ongoing: (g, c, add) => { if (!mine(g, c).length) add(c, 5); } }),
  Orka: M('+7 if it’s your only card here.', { ongoing: (g, c, add) => { if (!mine(g, c).length) add(c, 7); } }),
  Mojo: M('+6 if both sides here are full.', { ongoing: (g, c, add) => { if (g.full(c.lane, 'me') && g.full(c.lane, 'opp')) add(c, 6); } }),
  Warpath: M('+5 if any of your locations are empty.', { ongoing: (g, c, add) => { if ([0, 1, 2].some((l) => !g.at(l, c.side).length)) add(c, 5); } }),
  ManThing: M('3-Cost or less cards here have −2.', { ongoing: (g, c, add) => g.at(c.lane).filter((x) => x !== c && cost(g, x) <= 3).forEach((x) => add(x, -2)) }),
  USAgent: M('4-Cost or more cards here have −3.', { ongoing: (g, c, add) => g.at(c.lane).filter((x) => x !== c && cost(g, x) >= 4).forEach((x) => add(x, -3)) }),
  RedSkull: M('Enemy cards here have +2.', { ongoing: (g, c, add) => enemy(g, c).forEach((x) => add(x, 2)) }),
  TyphoidMary: M('Your other cards here have −2.', { ongoing: (g, c, add) => mine(g, c).forEach((x) => add(x, -2)) }),
  Diamondback: A('Afflicted enemy cards here have another −2.', { ongoing: (g, c, add) => enemy(g, c).filter((x) => x.buff < 0).forEach((x) => add(x, -2)) }),
  Ajax: M('+1 for each card in play with negative changes.', { ongoing: (g, c, add) => add(c, g.active().filter((x) => x.buff < 0).length) }),
  JackFlag: M('Your cards here with increased Power have +2.', { ongoing: (g, c, add) => mine(g, c).filter((x) => x.buff > 0).forEach((x) => add(x, 2)) }),
  Muse: A('+3 per location where your card was destroyed.', { ongoing: (g, c, add) => add(c, 3 * new Set(g.board.filter((x) => x.side === c.side && x.gone === 'destroyed').map((x) => x.lane)).size) }),
  WildChild: A('+4 if one of your cards was destroyed (discards not tracked).', { ongoing: (g, c, add) => { if (g.board.some((x) => x.side === c.side && x.gone === 'destroyed')) add(c, 4); } }),
  Ozymandias: M('Your Rocks have +3.', { ongoing: (g, c, add) => allies(g, c).filter((x) => x.id === 'Rock').forEach((x) => add(x, 3)) }),
  Moonstone: A('Has the Ongoing effects of your 3-Cost or less cards here.', { ongoing: (g, c, add) => mine(g, c).filter((x) => cost(g, x) <= 3).forEach((x) => g.abilityOf(x)?.ongoing?.(g, c, add)) }),
  SuperSkrull: A('Has the Ongoing effects of all enemy cards.', { ongoing: (g, c, add) => foes(g, c).forEach((x) => g.abilityOf(x)?.ongoing?.(g, c, add)) }),
  AntMan: M('+4 with a full side here.', { ongoing: (g, c, add) => { if (g.full(c.lane, c.side)) add(c, 4); } }),
  CyclopsXMen: A('Gains the most energy you had in a turn (counted as the turn number).', { ongoing: (g, c, add) => add(c, Math.min(6, g.turn)) }),
  StrongGuy: A('+6 with 1 or fewer cards in hand (not tracked).', {}),
  DevilDinosaur: A('+2 per card in hand (counted as 3 cards).', { ongoing: (g, c, add) => add(c, 6) }),
  Ronan: A('+2 per card in the opponent’s hand (counted as 3).', { ongoing: (g, c, add) => add(c, 6) }),
  Darkhawk: A('+2 per card in the opponent’s deck (counted from the turn).', { ongoing: (g, c, add) => add(c, 2 * Math.max(0, 9 - g.turn)) }),
  LivingTribunal: A('Splits your total Power evenly across locations; not applied.', {}),
  RedOnslaught: A('Has 3 random Ongoing abilities: set them on the board.', {}),
  Colossus: M('Can’t be destroyed, moved or reduced.'),
  Caiera: M('Your 1 and 6-Cost cards can’t be destroyed.'),
  Mercury: M('Enemy cards here can’t move.'),
  JoaquinTorres: M('Your 1-Costs’ On Reveals here repeat.'),
  ProfessorX: A('Locks this location; not enforced.', {}),
  Stardust: A('Cards can only be added by playing or moving; not enforced.', {}),
  Goose: A('Cards costing 4+ can’t be played here; not enforced.', {}),
  JeanGrey: A('First card each turn must go here; not enforced.', {}),
  InvisibleWoman: A('Your cards here stay hidden; enter their Power as you know it.', {}),
  EbonyMaw: A('You can’t play cards here; not enforced.', {}),
  JJonahJameson: N('Cosmetic.'),
  HowardTheDuck: N('Lets you peek at your deck.'),

  // ---- After cards are played / move / destroyed -----------------------
  Angela: M('+1 after you play a card here.', { allyPlayedHere: (g, c) => g.buff(c, 1) }),
  Bishop: M('+1 after you play a card.', { allyPlayed: (g, c) => g.buff(c, 1) }),
  Galacta: A('Your first card each turn at another location gets +2.', { allyPlayed: (g, c, p) => { if (p.lane !== c.lane && c.galactaTurn !== g.turn) { c.galactaTurn = g.turn; g.buff(p, 2); } } }),
  WerewolfByNight: A('Moves to your next On Reveal card and gains +2.', { allyPlayed: (g, c, p) => { if (/On Reveal/.test(text(g, p)) && g.move(c, p.lane, 'self')) g.buff(c, 2); } }),
  Surtur: M('+2 after you play a card with 10+ Power.', { allyPlayed: (g, c, p) => { if (g.power(p) >= 10) g.buff(c, 2); } }),
  FrankieRaye: M('Doubles after your next 6-Cost card.', { allyPlayed: (g, c, p) => { if (!c.frankie && cost(g, p) === 6) { c.frankie = true; g.buff(c, g.power(c)); } } }),
  NicholasScratch: A('+1 after you play a skill.', {}),
  Silk: A('Moves away after any card is played here.', { anyPlayedHere: (g, c) => g.move(c, freeLane(g, c.side, c.lane), 'self') }),
  Titania: M('Switches sides after any card is played here.', { anyPlayedHere: (g, c) => { if (!g.full(c.lane, other(c.side))) c.side = other(c.side); } }),
  Topaz: M('Your cards played here move to the middle.', { allyPlayedHere: (g, c, p) => g.move(p, 1) }),
  Xorn: M('3 and 4-Cost cards played here move away.', { anyPlayedHere: (g, c, p) => { if ([3, 4].includes(cost(g, p))) g.move(p, freeLane(g, p.side, c.lane)); } }),
  EzekielSims: A('After you play a stronger card here: +2 and moves away.', { allyPlayedHere: (g, c, p) => { if (g.power(p) > g.power(c)) { g.buff(c, 2); g.move(c, freeLane(g, c.side, c.lane), 'self'); } } }),
  RocketAndGroot: M('Steals 1 from each enemy card played here.', { anyPlayedHere: (g, c, p) => { if (p.side !== c.side) { g.buff(p, -1); g.buff(c, 1); } } }),
  Hawkeye: M('+4 if you play a card here next turn.', { allyPlayedHere: (g, c, p) => { if (!c.bonus && p.turn === c.turn + 1) { c.bonus = true; g.buff(c, 4); } } }),
  Rescue: M('+5 if you play a card here next turn.', { allyPlayedHere: (g, c, p) => { if (!c.bonus && p.turn === c.turn + 1) { c.bonus = true; g.buff(c, 5); } } }),
  HawkeyeAvengers: A('+1 if you play a card here next turn.', { allyPlayedHere: (g, c, p) => { if (!c.bonus && p.turn === c.turn + 1) { c.bonus = true; g.buff(c, 1); } } }),
  JessicaJones: M('+5 if you don’t play a card here next turn.', { allyPlayedHere: (g, c, p) => { if (p.turn === c.turn + 1) c.blocked = true; }, eot: (g, c) => { if (g.turn === c.turn + 1 && !c.blocked) g.buff(c, 5); } }),
  Agony: M('Merges into your next card played here.', { allyPlayedHere: (g, c, p) => { if (c.gone) return; g.buff(p, g.power(c)); c.gone = 'merged'; } }),
  AgonyWebSlingers: M('Merges into your next card played here.', { allyPlayedHere: (g, c, p) => { if (c.gone) return; g.buff(p, g.power(c)); c.gone = 'merged'; } }),
  Kraven: M('+2 when a card moves here.', { cardMovedHere: (g, c) => g.buff(c, 2) }),
  Kingpin: M('Enemy cards that move here get −2.', { cardMovedHere: (g, c, m) => { if (m.side !== c.side) g.buff(m, -2); } }),
  Hercules: A('Your first card moving here each turn moves on.', {}),
  SpiderPunk: M('Moveable once; steals 2 from the strongest enemy where it moves.', { move: (g, c) => { const t = enemy(g, c).sort(byPower(g))[0]; if (t) { g.buff(t, -2); g.buff(c, 2); } } }),
  SpiderMan2099: M('Moveable once; −3 to an enemy card where it moves.', { move: (g, c) => { const t = enemy(g, c).sort(byPower(g))[0]; if (t) g.buff(t, -3); } }),
  NightcrawlerXMen: A('Moveable once; +1 per X-Man where it moves (counted per card).', { move: (g, c) => g.buff(c, mine(g, c).length) }),
  Redwing: A('The first time it moves, adds a hand card to the old location (log it).', {}),
  Nocturne: A('Moveable once; changes its location when it moves (set the new one).', {}),
  JeffTheBabyLandShark: M('Moveable once: tap it on the board to move it.'),
  MaryJane: A('End of turn: your cards that moved this turn get +1.', { eot: (g, c) => allies(g, c).concat([c]).filter((x) => x.movedTurn === g.turn).forEach((x) => g.buff(x, 1)) }),
  Nova: M('When destroyed, your cards get +1.', { destroyed: (g, c) => allies(g, c).forEach((x) => g.buff(x, 1)) }),
  Nimrod: M('When destroyed, copies itself to each other location.', { destroyed: (g, c) => [0, 1, 2].filter((l) => l !== c.lane).forEach((l) => g.copy(c, l)) }),
  BuckyBarnes: M('When destroyed, becomes the Winter Soldier.', { destroyed: (g, c) => g.spawn(c.side, 'WinterSoldier', c.lane, null, c.uid) }),
  UncleBen: M('When destroyed, becomes Spider-Man.', { destroyed: (g, c) => g.spawn(c.side, 'SpiderMan', c.lane, null, c.uid) }),
  Sabretooth: M('Returns to hand when destroyed.', { destroyed: (g, c) => { c.gone = 'hand'; } }),
  Headpool: M('Returns to hand when destroyed.', { destroyed: (g, c) => { c.gone = 'hand'; } }),
  MoiraX: N('When destroyed, copies your opening hand.'),
  Marrow: A('When destroyed, −7 split among enemy cards.', { destroyed: (g, c) => { const f = foes(g, c); f.forEach((x) => g.buff(x, -7 / f.length)); } }),
  WadeWilson: A('When destroyed, replaced by a 1-Cost card (+2).', { destroyed: (g, c) => g.spawn(c.side, 'Squirrel', c.lane, Math.round(g.avgPower(1)) + 2, c.uid) }),
  AirWalker: A('When destroyed, replaced by a 4-Cost card.', { destroyed: (g, c) => g.spawn(c.side, 'Squirrel', c.lane, Math.round(g.avgPower(4)), c.uid) }),
  Firehair: A('Uses the On Reveal of your destroyed cards.', { allyDestroyed: (g, c, d) => g.runReveal(d, g.abilityOf(d), c) }),
  Angel: A('Replaces your destroyed cards from hand or deck; log it.', {}),

  // ---- End of turn ------------------------------------------------------
  Thena: A('+3 if you played exactly 2 cards this turn.', { eot: (g, c) => { if (g.playedThisTurn(c.side).length === 2) g.buff(c, 3); } }),
  Moondragon: A('+2 if you played 1 card and spent all energy.', { eot: (g, c) => { if (g.playedThisTurn(c.side).length === 1) g.buff(c, 2); } }),
  TheThingFirstSteps: A('End of turn: +2 (the full-side destroy isn’t applied).', { eot: (g, c) => g.buff(c, 2) }),
  Havok: M('End of turn: +3 (you lose 1 max energy).', { eot: (g, c) => g.buff(c, 3) }),
  Attuma: A('End of turn: destroys one of your weaker cards here.', { eot: (g, c) => { const t = lowest(g, mine(g, c).filter((x) => g.power(x) < g.power(c))); if (t) g.destroy(t); } }),
  Lockheed: A('After you play a 1-Cost: −2 to an enemy card here.', { eot: (g, c) => { if (g.playedThisTurn(c.side).some((x) => cost(g, x) === 1)) { const t = enemy(g, c).sort(byPower(g))[0]; if (t) g.buff(t, -2); } } }),
  DraxAvatarOfLife: A('+3 if the opponent played a stronger card this turn.', { eot: (g, c) => { if (g.playedThisTurn(other(c.side)).some((x) => g.power(x) > g.power(c))) g.buff(c, 3); } }),
  Doom2099: A('Adds a DoomBot 2099 if you played exactly 1 card.', { eot: (g, c) => { if (g.playedThisTurn(c.side).length === 1) { const l = freeLane(g, c.side); if (l != null) g.spawn(c.side, 'DoomBot2099', l, null, c.uid); } } }),
  GalactusFirstSteps: A('+2 while winning its Herald’s location (counted while winning here).', { eot: (g, c) => { if (winning(g, c)) g.buff(c, 2); } }),
  RedHulk: A('+3 if the opponent has unspent energy (not tracked).', {}),
  StrangeSupreme: A('Merges your created cards (+2 each); adjust by hand.', {}),
  BruceBanner: A('33% to Hulk out with unspent energy; adjust by hand.', {}),
  ZombiePowerMan: N('Discards from hand while winning.'),
  ThaddeusRoss: N('Draws when the opponent leaves energy.'),
  MadThinker: A('+2 with a full hand (not tracked).', {}),
  JimHammond: A('Gains from bonus energy (not tracked).', {}),
  WolverineXMen: A('+2 with bonus energy (not tracked).', {}),
  SuperiorSpiderMan: N('+1 energy with buffed cards in play.'),
  ProfessorXXMen: N('Energy per X-Man here.'),
  Eson: A('Puts a created card from hand here each turn; log it.', {}),
  Makkari: A('Runs from hand to a random location; log it when it lands.', {}),

  // ---- Activate (you trigger them; adjust by hand) -----------------------
  KidOmega: A('Activate: destroys your next card to gain its Power; adjust by hand.', {}),
  Arana: A('Activate: next card +1 and moves right; adjust by hand.', {}),
  Chamber: A('Activate: +2 per 5-Cost+; adjust by hand.', {}),
  InvisibleWomanFirstSteps: A('Activate: repeats End of Turn abilities; adjust by hand.', {}),
  Sparky: A('Activate: moves your last-moved card back with +2; adjust by hand.', {}),
  Bullseye: A('Activate: −2 to enemy cards; adjust by hand.', {}),
  KarimaShapandar: A('Activate: −7 to the strongest enemy; adjust by hand.', {}),
  Jocasta: A('Activate: activates your cards here; adjust by hand.', {}),
  Askanison: A('Activate: creates a card at another location; log it.', {}),
  FenrisWolf: A('Activate: resurrects their strongest destroyed card on your side; log it.', {}),
  ScarletSpider: A('Activate: clones itself to another location; log it.', {}),
  ScarletSpiderWebSlingers: A('Activate: clones itself and moves; log it.', {}),
  Lasher: A('Activate: afflicts an enemy here with its Power; adjust by hand.', {}),
  Danger: A('Activate: destroys a weaker enemy here; destroy it on the board.', {}),
  Cobra: A('Activate: destroys an enemy created card here; destroy it on the board.', {}),
  FanFei: A('Activate: your other cards here +1 and move right; adjust by hand.', {}),
  Fantasticar: A('Activate: your End of Turn cards +2; adjust by hand.', {}),
  Fantomex: A('Activate: −2 to front-row enemies; adjust by hand.', {}),
  ZombieCaptainMarvel: A('Activate: destroys your others here, +3 each, then moves; adjust by hand.', {}),
  Magus: A('Activate: copies a deck card’s text; set its ability on the board.', {}),
  Herbie: A('Changing Activate ability; adjust by hand.', {}),
  HerbieChampion: A('Changing Activate ability; adjust by hand.', {}),
  Hellcow: N('Activate: discards from hand.'),
  BlackWidow: N('Activate: gives the opponent a Widow’s Bite.'),
  BlackSwan: N('Activate: makes your 1-Costs free.'),
  Warlock: N('Activate: cheaper cards in hand.'),
  JenniferKale: N('Activate: +1 energy next turn.'),
  SymbioteSpiderManWebSlingers: A('Activate: merges a card here; adjust by hand.', {}),
  Boomerang: A('Activate: returns to hand; remove it from the board.', {}),
  SuperAdaptoid: A('Steals an enemy Activate here; set its ability on the board.', {}),

  // ---- Objectives --------------------------------------------------------
  GambitHorseman: A('Objective: destroys enemy cards; destroy them on the board.', {}),
  StormHorseman: A('Objective: +2 to your cards here; adjust by hand.', {}),
  WolverineHorseman: A('Objective: +4 at each location; adjust by hand.', {}),
  PolarisHorseman: A('Objective: puts a hand card here; log it.', {}),
  SeleneHorseman: A('Objective: steals 5 Power; adjust by hand.', {}),
  ArchangelHorseman: A('Objective: resurrects with +5; log it.', {}),
  JuggernautHorseman: A('Objective: +6; adjust by hand.', {}),
  Stryfe: A('Objective: uses an On Reveal from hand; adjust by hand.', {}),
  PunisherWarMachine: N('Objective: +1 max energy.'),
  SinisterSix: A('Objective: merges six cards; log it.', {}),

  // ---- Random / copied text (set its ability on the board) ---------------
  ZombieScarletWitch: A('Horde isn’t tracked; adjust by hand.', {}),
  Kang: A('Becomes Kangs with random text: set its ability on the board.', {}),
  Hulkling: A('Copies a random 6-Cost’s text: set its ability on the board.', {}),
  Copycat: A('Copies a card’s text when drawn: set its ability on the board.', {}),
  AstralProjection: A('Copies an On Reveal from hand: set its ability on the board.', {}),
  Prodigy: A('Copies the text in front of it: set its ability on the board.', {}),
  RamaTut: A('Uses 3 old On Reveals: set its abilities on the board.', {}),
  MystiqueBrotherhoodOfMutants: A('Copies a Brotherhood card here: set its ability on the board.', {}),
  ScarletWitchQueenOfChaos: A('Adds a random skill to your hand each turn: log it with "+ Add card" (Custom if it’s not listed).', {}),
  ZombieGalacti: A('Turns 6 deck cards into copies of itself.', {}),
  TechnoOrganicVirus: A('Replaces your other cards’ text here: not applied.', {}),

  // ---- Not on the board ----------------------------------------------------
  Hood: N(DRAW), CorvusGlaive: N(ENERGY), JubileeSilverSurfer: N(HAND), Loki: N(DECK), Scorn: A('When discarded, +2 to itself and a card in play; adjust by hand.', {}),
  Gwenpool: N(HAND), Okoye: N(DECK), Apocalypse: N(HAND), Frigga: N(DRAW), Crossbones: N(PLAYRULE), ProximaMidnight: A('Jumps to your weakest location when discarded; log it.', {}),
  Nakia: N(HAND), Mirage: N(DRAW), Sandman: N(COST), Yondu: N(DECK), MadameWeb: A('Makes one of your cards here Moveable: move it on the board.', {}),
  InfinityUltron: N(DRAW), GhostRider: A('Brings back a discarded card here: log it.', {}), DoctorOctopusFracturedFrontier: N(DECK), Selene: N(HAND),
  Sentinel: N(DRAW), AgentCoulson: N(DRAW), Daredevil: N('Shows the opponent’s turn 5 plays first.'), Khonshu: A('Resurrects a discarded card here at 5 Power: log it.', {}),
  Hela: A('Resurrects discarded cards: log them.', {}), Bast: N(HAND), MariaHill: N(DRAW), ColleenWing: N(DISCARD), Agent13: N(DRAW),
  SilverSable: A('Steals 2 Power from their deck (+2 here).', { reveal: (g, c) => g.buff(c, 2) }), WilsonFisk: N(COST), Echo: M('Strips their next Ongoing card here.', { anyPlayedHere: (g, c, p) => { if (p.side !== c.side && /Ongoing/.test(text(g, p))) p.silenced = true; } }),
  Ikari: N(PLAYRULE), KateBishop: N(DRAW), Daken: N(DRAW), CullObsidian: N(PLAYRULE), SheHulk: N(COST), MoonKnight: N(DISCARD), BlackCat: N(DISCARD),
  Swarm: N(DRAW), BetaRayBill: N(DECK), PeniParker: N(DRAW), Supergiant: A('Next turn’s plays stay hidden: enter their Power as you learn it.', {}),
  Pixie: N(DECK), Terrax: N(DECK), NickFury: N(DRAW), Miek: N(HAND), BlackBolt: N(DISCARD), Thor: N(DECK), Stature: N(COST), Clea: N(DRAW), Snowguard: N(DRAW),
  HopeSummers: N(ENERGY), FallenOne: N(ENERGY), MonstroOctopus: N(COST), Prowler: N(DRAW), HydroMan: N(DECK), Korg: N(DECK), MasterMold: N(DRAW),
  AgathaHarkness: A('Plays your cards for you on even turns.', {}), SilverSurferFirstSteps: A('Copies an On Reveal while winning here: set its ability on the board.', {}),
  WeaponH: N(HAND), Maximus: N(DRAW), WhiteQueen: N(DRAW), Dormammu: N(DRAW), Bastion: N(DRAW), Rockslide: N(DECK), Hellion: A('Makes your cards Moveable here next turn: move them on the board.', {}),
  MilesMorales: N(COST), SubMariner: N(DRAW), Storm: A('Floods this location: no plays here after next turn (not enforced).', {}), Agamotto: N(DECK),
  AntiVenom: N(DECK), Cloak: A('Makes cards Moveable here next turn: move them on the board.', {}), StarlordMasterOfTheSun: N(ENERGY), RedShift: N(HAND),
  SilverSamurai: N(DISCARD), Sersi: A('Transforms your other cards here: set what they became on the board.', {}), DragonOfTheMoon: N(HAND),
  SpiderManNoir: A('May add a top-deck card here: log it.', {}), Sauron: N(DECK), EntropicHavok: N(ENERGY), EsmeCuckoo: N(DRAW), Namorita: N(COST),
  Zero: A('Removes the abilities of your next card.', { reveal: (g, c) => pend(g, c, 'Zero: next card has no ability', (g2, p) => { p.silenced = true; }) }),
  WebSling: A('Makes one of your cards here Moveable (+1 when it moves): move it on the board.', {}), ShangChiMasterOfTheRings: N(DRAW), AgentVenom: N(DECK), SwordMaster: N(DISCARD), Gorgon: N(COST),
  Mantis: N(DRAW), GhostThunderbolts: N(COST), Sandstorm: N(DRAW), Quake: A('Swaps the other two locations: swap them in the lanes.', {}),
  Leech: N('Removes text from 6-Costs in their hand.'), ToxieDoxie: N(HAND), MoleMan: N(DRAW), AuntMay: N(HAND), MorganLeFay: N(DRAW),
  MajorVictory: N(DRAW), Quicksand: N(ENERGY), ColonelAmerica: A('+1 to your others here per discard turn (not tracked).', {}), BaronMordo: N(COST),
  Helicarrier: N(DRAW), Mephisto: N('Doubles winnings.'), Uatu: N('Shows unrevealed locations.'), Nightmare: N(HAND),
  JeanGreyXMen: N(DRAW), MantisGuardiansOfTheGalaxy: N(COST), RocketRaccoonGuardiansOfTheGalaxy: N(DRAW), StarlordGuardiansOfTheGalaxy: A('+1 to your Guardians if they played here (not tracked).', {}),
  GrootGuardiansOfTheGalaxy: N(DISCARD), ThorAvengers: N(DRAW), ToxieDoxieThunderbolts: N(HAND), ValentinaThunderbolts: N(DRAW), VisionAvengers: A('Moveable with another Avenger here: move it on the board.', {}),
  WhiteQueenBrotherhoodOfMutants: N(DRAW), WinterSoldierThunderbolts: N(PLAYRULE), ScarletWitchBrotherhoodOfMutants: N('Changes a location (pick the new one).'),
  SeleneBrotherhoodOfMutants: N(HAND), AntiVenomWebSlingers: N(DECK), SpiderMan2099WebSlingers: A('+1 per move this game to one of your cards; adjust by hand.', {}), Tarantula: A('Grows when it has the highest Power; adjust by hand.', {}),
};

// Champion and team variants that share a base card's ability.
const ALIAS = {
  BlackPantherChampion: 'BlackPanther', CaptainAmericaChampion: 'CaptainAmerica', CarnageChampion: 'Carnage', DrDoomChampion: 'DrDoom',
  GhostSpiderChampion: 'GhostSpider', HumanTorchFirstStepsChampion: 'HumanTorchFirstSteps', IronManChampion: 'IronMan', MagnetoChampion: 'Magneto',
  MrFantasticChampion: 'MrFantastic', RocketRaccoonChampion: 'RocketRaccoon', TheThingFirstStepsChampion: 'TheThingFirstSteps', AnnihilusChampion: 'Annihilus',
  InvisibleWomanChampion: 'InvisibleWoman', MoleManChampion: 'MoleMan', SentinelChampion: 'Sentinel', ThanosChampion: 'Thanos', ThorChampion: 'Thor',
};
export function addAliases(table) {
  for (const [id, base] of Object.entries(ALIAS)) if (!table[id] && table[base]) table[id] = table[base];
  return table;
}
